build:
  maxIssues: 0

style:
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**']
    ignoreNumbers: [-1, 0, 1, 2, 3, 5, 8, 10, 16, 24, 32, 60, 100, 1000]
    ignorePropertyDeclaration: true
    ignoreNamedArgument: true

complexity:
  Long ParameterList:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**' ]
    LongMethod:
      active: true
      excludes: [ '**/test/**', '**/androidTest/**' ]
      threshold: 60  # Lines of code. Adjust as needed.
    LargeClass:
      active: true
      excludes: [ '**/test/**', '**/androidTest/**' ]
      threshold: 600 # Lines of code. Adjust.
    ComplexMethod:
      active: true
      excludes: [ '**/test/**', '**/androidTest/**' ]
      threshold: 15 # Cyclomatic complexity. Adjust.
    TooManyFunctions:
      active: true
      excludes: [ '**/test/**', '**/androidTest/**' ]
      threshold: 11 # Top-level functions in a file
    NestedBlockDepth:
      active: true
      threshold: 4

  naming:
    ClassNaming:
      active: true
      classPattern: '[A-Z][a-zA-Z0-9]*'
    FunctionNaming:
      active: true
      functionPattern: '[a-z][a-zA-Z0-9]*'
    VariableNaming:
      active: true
      variablePattern: '[a-z][a-zA-Z0-9]*'
    PackageNaming:
      active: true
      packagePattern: '[a-z][a-z.]*'

  comments:
    CommentOverPrivateFunction:
      active: false # I prefer documenting public API
    CommentOverPrivateProperty:
      active: false

  empty-blocks:
    EmptyFunctionBlock:
      active: false