build:
  maxIssues: 1000    # Allow a large number of issues initially.  Reduce this over time!

style:
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**']
    ignoreNumbers: ['-1', '0', '1', '2', '3', '4','5', '6', '7', '8', '9', '10', '12', '16', '18', '20', '22', '23', '24', '26', '27', '28', '30', '31', '32', '33', '34', '35', '36', '40', '44', '53', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72' ,'73', '75', '76', '77', '78', '79', '80', '81', '83', '86', '88', '89', '90', '96',  '100', '111', '113', '114', '117', '118', '128',  '157', '168', '180','183', '210', '349', '358','1000', '1003', '1006', '1009', '1012', '1013', '1014', '1015', '1016', '1018',  '1030', '1063', '1066', '1069', '1072', '1087', '1114', '1117', '1135', '1147', '1150', '1153', '1168', '1171', '1180', '1183', '1186', '1189', '1192', '1195', '1198', '1201', '1204', '1207', '1210', '1213', '1216', '1219', '1222', '1225', '1237', '1240', '1243', '1246', '1249', '1252', '1255', '1258', '1261', '1264', '1273', '1276', '1279', '1282', '2022', '2643743', '3163858', '7200', '1661834187', '1661882248', '1661871600', '1661882400', '1661893200', '1662292800', '1647345600', '1647356400', '1647367200', '1647766800']
    ignorePropertyDeclaration: true
    ignoreNamedArgument: true


  WildcardImport:
    active: true

  MaxLineLength:
    active: true
    maxLineLength: 160
    excludeCommentStatements: true

  NewLineAtEndOfFile:
    active: true

complexity:
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: false
  LongMethod:
    active: true
    threshold: 80
  LargeClass:
    active: true
    threshold: 800
  CyclomaticComplexMethod:
    active: true
    threshold: 20
  TooManyFunctions:
    active: true
    excludes: ['**/test/**', '**/androidTest/**']
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: true
  NestedBlockDepth:
    active: true
    threshold: 5

naming:
  ClassNaming:
    active: false

  FunctionNaming:
    active: false
  VariableNaming:
    active: false

  PackageNaming:
    active: true
    packagePattern: '[a-z][a-z.]*'

comments:
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: true